from fastapi.testclient import TestClient

from app.main import app
from app.services.accounting_engine import prepare_accounting_data
from app.services.accounting_templates import list_accounting_templates
from app.template_engine import generate_document


def _invoice_template():
    return next(
        item
        for item in list_accounting_templates()
        if item["documentType"] == "invoice"
        and item["stylePreset"] == "executive-navy"
    )


def _data():
    return {
        "company": {"name": "Generator Test Ltd"},
        "counterparty": {"name": "Customer One"},
        "recipient": {"name": "Customer One", "address": "Maseru"},
        "document": {
            "number": "INV-2026-000777",
            "reference": "ORDER-777",
            "date": "2026-09-18",
            "currency": "USD",
            "notes": "Generated by the accounting issuance engine.",
        },
        "items": [
            {
                "description": "Consulting",
                "quantity": 2,
                "unitPrice": 100,
                "discount": 10,
                "taxRate": 15,
            },
            {
                "description": "Administration",
                "quantity": 1,
                "unitPrice": 50,
                "taxRate": 0,
            },
        ],
        "totals": {"amountPaid": 100},
        "approval": {"preparedBy": "Finance", "approvedBy": "Manager"},
        "verification": {"url": "https://verify.example.test/inv-777"},
    }


def _nodes(node):
    yield node
    for child in node.get("content") or []:
        yield from _nodes(child)


def test_accounting_engine_recalculates_sales_totals():
    template = _invoice_template()
    prepared = prepare_accounting_data(template, _data())
    assert prepared["totals"] == {
        "amountPaid": 100,
        "subtotal": 250.0,
        "discount": 10.0,
        "tax": 28.5,
        "total": 268.5,
        "balanceDue": 168.5,
    }
    assert prepared["items"][0]["total"] == 218.5


def test_template_resolution_uses_selected_currency_and_resolves_qr_attributes():
    template = _invoice_template()
    data = prepare_accounting_data(template, _data())
    data["verification"]["code"] = "ITH-INV-TEST"
    document = generate_document(template["document"], data)
    text = " ".join(
        str(node.get("text") or "")
        for node in _nodes(document["body"])
        if node.get("type") == "text"
    )
    assert "USD 268.50" in text
    qr = next(node for node in _nodes(document["body"]) if node.get("type") == "qrCode")
    assert qr["attrs"]["value"] == "https://verify.example.test/inv-777"


def test_accounting_generator_api_previews_and_issues_backend_files():
    template = _invoice_template()
    with TestClient(app) as client:
        form = client.get(f"/v1/accounting/templates/{template['id']}/form")
        assert form.status_code == 200
        assert form.json()["family"] == "sales"
        assert form.json()["collectionPath"] == "items"

        preview = client.post(
            "/v1/accounting/preview",
            json={"templateId": template["id"], "data": _data()},
        )
        assert preview.status_code == 200
        payload = preview.json()
        assert payload["data"]["totals"]["total"] == 268.5
        assert payload["data"]["verification"]["code"].startswith("ITH-INV-")

        pdf = client.post(
            "/v1/accounting/render",
            json={
                "templateId": template["id"],
                "data": payload["data"],
                "format": "pdf",
                "persist": True,
            },
        )
        assert pdf.status_code == 200
        assert pdf.content.startswith(b"%PDF")
        assert pdf.headers["x-ithute-document-id"]
        assert pdf.headers["x-ithute-verification-code"].startswith("ITH-INV-")

        docx = client.post(
            "/v1/accounting/render",
            json={
                "templateId": template["id"],
                "data": payload["data"],
                "format": "docx",
                "persist": False,
            },
        )
        assert docx.status_code == 200
        assert docx.content.startswith(b"PK")
